<a href="https://colab.research.google.com/github/ahmedkhanpakistani5-hash/-intern-feedback-to-understand-positive-and-negative-sentiments./blob/main/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ahmedkhanpakistani5-hash/ahmad-flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [ ]:
from google.colab import userdata
HF_TOKEN = userdata.get('HF_TOKEN')

import pandas as pd
from huggingface_hub import hf_hub_download

MONTH = "2026-03"
path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    repo_type="dataset",
    filename=f"fact_content_daily_performance/month={MONTH}/data_0.parquet",
    token=HF_TOKEN,
)
df = pd.read_parquet(path)

print("rows:", len(df))
print(df.dtypes)
df.head()

rows: 9841378
report_date                  object
client_hash_id               object
content_hash_id              object
client_has_gsc                 bool
client_has_ga4                 bool
gsc_data_available             bool
ga4_data_available           object
gsc_impressions               int64
gsc_clicks                    int64
gsc_sum_position              int64
gsc_avg_position            float64
ga4_pageviews               float64
ga4_sessions                float64
ga4_users                   float64
ga4_engaged_sessions        float64
ga4_total_engagement_sec    float64
sessions_organic            float64
sessions_direct             float64
sessions_referral           float64
sessions_social             float64
sessions_paid               float64
sessions_ai                 float64
ai_chatgpt                  float64
ai_perplexity               float64
ai_gemini                   float64
ai_copilot                  float64
ai_claude                   float64
ai_meta                     float64
ai_other                    float64
scroll_events               float64
dtype: object

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20,0,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125,1,616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7,0,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11,0,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

Unit of analysis (Grain): One row represents the aggregated performance metrics (impressions, clicks, average_position) for a unique combination of date, query, device, and country.
Time window: The dataset spans a 30-day window starting from 2023-10-01 to 2023-10-30 inclusive.

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

### **Section 2 Field Categorization**

* - Feature(s): [column] ([why it's knowable at the decision moment]), ...
- Label: [column] ([exact definition and the time window it covers])
- Context: [column] ([used only to filter or group, not as a model input]), e.g. date, client id
- Excluded:
  - [column]: Why? [one reason, e.g. "same-day outcome, would leak the label"]
  - [column]: Why? [e.g. "~15% null and not available at prediction time"]

In [ ]:
from google.colab import userdata
HF_TOKEN = userdata.get('HF_TOKEN')

import pandas as pd
from huggingface_hub import hf_hub_download

MONTH = "2026-03"
path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    repo_type="dataset",
    filename=f"fact_content_daily_performance/month={MONTH}/data_0.parquet",
    token=HF_TOKEN,
)
df = pd.read_parquet(path)

print("rows:", len(df))

# one line per column: type, % null, number of distinct values
summary = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "pct_null": (df.isna().mean() * 100).round(1),
    "n_unique": df.nunique(),
})
print(summary)

df.head()

rows: 9841378
                            dtype  pct_null  n_unique
report_date                object       0.0        31
client_hash_id             object       0.0        55
content_hash_id            object       0.0    331437
client_has_gsc               bool       0.0         1
client_has_ga4               bool       0.0         2
gsc_data_available           bool       0.0         2
ga4_data_available         object      30.7         2
gsc_impressions             int64       0.0      4854
gsc_clicks                  int64       0.0       140
gsc_sum_position            int64       0.0     34343
gsc_avg_position          float64      63.3    457684
ga4_pageviews             float64      30.7       234
ga4_sessions              float64      30.7       219
ga4_users                 float64      30.7       224
ga4_engaged_sessions      float64      30.7        18
ga4_total_engagement_sec  float64      30.7      1196
sessions_organic          float64      30.7       125
sessions_direct           float64      30.7        42
sessions_referral         float64      30.7        23
sessions_social           float64      30.7        12
sessions_paid             float64      30.7        52
sessions_ai               float64      30.7        16
ai_chatgpt                float64      30.7        15
ai_perplexity             float64      30.7         9
ai_gemini                 float64      30.7        11
ai_copilot                float64      30.7         6
ai_claude                 float64      30.7         8
ai_meta                   float64      30.7         1
ai_other                  float64      30.7         1
scroll_events             float64      30.7        66

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20,0,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125,1,616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7,0,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11,0,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*
- Grain check: [one sentence on what one row should be] and how many duplicates exist.
- Counts: row count and date span of my slice for month=2026-03.
- Availability: how many rows survive when I filter with IS TRUE on [flag column].

In [ ]:
from google.colab import userdata
HF_TOKEN = userdata.get('HF_TOKEN')

import pandas as pd
from huggingface_hub import hf_hub_download

MONTH = "2026-03"
path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    repo_type="dataset",
    filename=f"fact_content_daily_performance/month={MONTH}/data_0.parquet",
    token=HF_TOKEN,
)
df = pd.read_parquet(path)

summary = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "pct_null": (df.isna().mean() * 100).round(1),
    "n_unique": df.nunique(),
})
print(summary)
display(df.head())

                            dtype  pct_null  n_unique
report_date                object       0.0        31
client_hash_id             object       0.0        55
content_hash_id            object       0.0    331437
client_has_gsc               bool       0.0         1
client_has_ga4               bool       0.0         2
gsc_data_available           bool       0.0         2
ga4_data_available         object      30.7         2
gsc_impressions             int64       0.0      4854
gsc_clicks                  int64       0.0       140
gsc_sum_position            int64       0.0     34343
gsc_avg_position          float64      63.3    457684
ga4_pageviews             float64      30.7       234
ga4_sessions              float64      30.7       219
ga4_users                 float64      30.7       224
ga4_engaged_sessions      float64      30.7        18
ga4_total_engagement_sec  float64      30.7      1196
sessions_organic          float64      30.7       125
sessions_direct           float64      30.7        42
sessions_referral         float64      30.7        23
sessions_social           float64      30.7        12
sessions_paid             float64      30.7        52
sessions_ai               float64      30.7        16
ai_chatgpt                float64      30.7        15
ai_perplexity             float64      30.7         9
ai_gemini                 float64      30.7        11
ai_copilot                float64      30.7         6
ai_claude                 float64      30.7         8
ai_meta                   float64      30.7         1
ai_other                  float64      30.7         1
scroll_events             float64      30.7        66

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20,0,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125,1,616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7,0,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11,0,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*


Limitation: [what this slice cannot tell me], because [the measured fact with its number].
Effect on modeling: [what could go wrong, e.g. "a few large clients dominate the rows, so the model learns them, not the average client"].

In [ ]:
from google.colab import userdata
HF_TOKEN = userdata.get('HF_TOKEN')

import pandas as pd
from huggingface_hub import hf_hub_download

MONTH = "2026-03"
path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    repo_type="dataset",
    filename=f"fact_content_daily_performance/month={MONTH}/data_0.parquet",
    token=HF_TOKEN,
)
df = pd.read_parquet(path)

print("columns:", list(df.columns))

# 1) how empty is each column?
print("\n% null per column (top 10):")
print((df.isna().mean() * 100).round(1).sort_values(ascending=False).head(10))

# 2) how unevenly are rows spread across clients?
client_cols = [c for c in df.columns if "client" in c.lower()]
print("\nclient-like columns found:", client_cols)

if client_cols:
    per_client = df[client_cols[0]].value_counts()
    print("clients:", per_client.size)
    print("rows per client: min", per_client.min(),
          "| median", per_client.median(),
          "| max", per_client.max())
else:
    print("No column with 'client' in its name. Look at the column list above.")

columns: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

% null per column (top 10):
gsc_avg_position      63.3
ga4_data_available    30.7
ga4_sessions          30.7
ga4_pageviews         30.7
ga4_users             30.7
ai_chatgpt            30.7
sessions_ai           30.7
sessions_paid         30.7
sessions_social       30.7
sessions_referral     30.7
dtype: float64

client-like columns found: ['client_hash_id', 'client_has_gsc', 'client_has_ga4']
clients: 55
rows per client: min 341 | median 83119.0 | max 988497

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.